"""empty message

Revision ID: d6930b8a7050
Revises: 
Create Date: 2021-09-21 11:26:09.368207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6930b8a7050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('city', sa.String(length=120), nullable=False),
        sa.Column('state', sa.String(length=120), nullable=False),
        sa.Column('phone', sa.String(length=120), nullable=False),
        sa.Column('image_link', sa.String(length=500), nullable=True),
        sa.Column('facebook_link', sa.String(length=120), nullable=True),
        sa.Column('website_link', sa.String(length=120), nullable=True),
        sa.Column('venue_hunting', sa.Boolean(), nullable=False),
        sa.Column('venue_description', sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('genres', sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('city', sa.String(length=120), nullable=False),
        sa.Column('state', sa.String(length=120), nullable=False),
        sa.Column('address', sa.String(length=120), nullable=False),
        sa.Column('phone', sa.String(length=120), nullable=True),
        sa.Column('image_link', sa.String(length=500), nullable=True),
        sa.Column('facebook_link', sa.String(length=500), nullable=True),
        sa.Column('website_link', sa.String(length=500), nullable=True),
        sa.Column('talent_hunting', sa.Boolean(), nullable=False),
        sa.Column('talent_description', sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_genres',
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
        sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
        sa.PrimaryKeyConstraint('genre_id', 'artist_id')
    )
    op.create_table('shows_list',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('venue_id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('event_time', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
        sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_genres',
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.Column('venue_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
        sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
        sa.PrimaryKeyConstraint('genre_id', 'venue_id')
    )
    
    #& Insert Data
    
    #~ Insert into Artists
    op.execute('INSERT INTO artists (id, name, city, state, phone, image_link, facebook_link, website_link, venue_hunting, venue_description ) VALUES (\'1\', \'Guns N Petals\', \'San Francisco\', \'CA\', \'326-123-5000\', \'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80\', \'https://www.facebook.com/GunsNPetals\', \'https://www.gunsnpetalsband.com\', \'True\', \'Looking for shows to perform at in the San Francisco Bay Area!\');')
        # "genres": ["Rock n Roll"],

    op.execute('INSERT INTO artists (id, name, city, state, phone, image_link, facebook_link, website_link, venue_hunting, venue_description ) VALUES (\'2\', \'Matt Quevedo\', \'New York\', \'NY\', \'300-400-5000\', \'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80\', \'https://www.facebook.com/mattquevedo923251523\', \'\', \'False\', \'\');')
        # "genres": ["Jazz"],

    op.execute('INSERT INTO artists (id, name, city, state, phone, image_link, facebook_link, website_link, venue_hunting, venue_description ) VALUES (\'3\', \'The Wild Sax Band\', \'San Francisco\', \'CA\', \'432-325-5432\', \'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80\', \'\', \'\', \'False\', \'\');')
        # "genres": ["Jazz", "Classical"],    
    
    # op.execute('INSERT INTO artists (id, name, city, state, phone, image_link, facebook_link, website_link, venue_hunting, venue_description ) VALUES (\'2\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\');')
    
    #~ Insert into Venues
    op.execute('INSERT INTO venues (id, name, city, state, address, phone, image_link, facebook_link, website_link, talent_hunting, talent_description ) VALUES (\'1\', \'The Musical Hop\', \'San Francisco\', \'CA\', \'1015 Folsom Street\', \'123-123-1234\', \'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60\', \'https://www.facebook.com/TheMusicalHop\', \'https://www.themusicalhop.com\', \'True\', \'We are on the lookout for a local artist to play every two weeks. Please call us.\');')
        # "genres": ["Jazz", "Reggae", "Swing", "Classical", "Folk"],

    op.execute('INSERT INTO venues (id, name, city, state, address, phone, image_link, facebook_link, website_link, talent_hunting, talent_description ) VALUES (\'2\', \'The Dueling Pianos Bar\', \'New York\', \'NY\', \'335 Delancey Street\', \'914-003-1132\', \'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80\', \'https://www.facebook.com/theduelingpianos\', \'https://www.theduelingpianos.com\', \'False\', \'\');')
        # "genres": ["Classical", "R&B", "Hip-Hop"],

    
    op.execute('INSERT INTO venues (id, name, city, state, address, phone, image_link, facebook_link, website_link, talent_hunting, talent_description ) VALUES (\'3\', \'Park Square Live Music & Coffee\', \'San Francisco\', \'CA\', \'34 Whiskey Moore Ave\', \'415-000-1234\', \'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80\', \'https://www.facebook.com/ParkSquareLiveMusicAndCoffee\', \'https://www.parksquarelivemusicandcoffee.com\', \'False\', \'\');')
        # "genres": ["Rock n Roll", "Jazz", "Classical", "Folk"],

    # op.execute('INSERT INTO venues (id, name, city, state, address, phone, image_link, facebook_link, website_link, talent_hunting, talent_description ) VALUES (\'2\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\', \'Uncategorized\');')
    
    #~ Insert into Shows
    op.execute('INSERT INTO shows_list (venue_id, artist_id, event_time) VALUES (\'1\', \'1\', \'2019-05-21T21:30:00.000Z\');')

    op.execute('INSERT INTO shows_list (venue_id, artist_id, event_time) VALUES (\'3\', \'2\', \'2019-06-15T23:00:00.000Z\');')
    
    op.execute('INSERT INTO shows_list (venue_id, artist_id, event_time) VALUES (\'3\', \'3\', \'2035-04-01T20:00:00.000Z\');')
    
    op.execute('INSERT INTO shows_list (venue_id, artist_id, event_time) VALUES (\'3\', \'3\', \'2035-04-08T20:00:00.000Z\');')
    
    op.execute('INSERT INTO shows_list (venue_id, artist_id, event_time) VALUES (\'3\', \'3\', \'2035-04-15T20:00:00.000Z\');')
    
    # op.execute('INSERT INTO shows_list (venue_id, artist_id, event_time) VALUES (\'Uncategorized\', \'Uncategorized\', \'Uncategorized\');')
    
    
    #~ Insert into Genres
    op.execute('INSERT INTO genres (genres) VALUES (\'Alternative\'), (\'Blues\'), (\'Classical\'), (\'Country\'), (\'Electronic\'), (\'Folk\'), (\'Funk\'), (\'Hip-Hop\'), (\'Heavy Metal\'), (\'Instrumental\'), (\'Jazz\'), (\'Musical Theatre\'), (\'Pop\'), (\'Punk\'), (\'R&B\'), (\'Reggae\'), (\'Rock n Roll\'), (\'Soul\'), (\'Swing\'), (\'Other\');')

    #~ Insert into artist_genres
    op.execute('INSERT INTO artist_genres (genre_id, artist_id) VALUES (\'17\', \'1\');')
    
    op.execute('INSERT INTO artist_genres (genre_id, artist_id) VALUES (\'11\', \'2\');')
    
    op.execute('INSERT INTO artist_genres (genre_id, artist_id) VALUES (\'11\', \'3\');')
    
    op.execute('INSERT INTO artist_genres (genre_id, artist_id) VALUES (\'3\', \'3\');')
    
    # op.execute('INSERT INTO artist_genres (genre_id, artist_id) VALUES (\'Uncategorized\', \'Uncategorized\');')
    
    
    #~ Insert into venue_genres
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'11\', \'1\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'16\', \'1\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'19\', \'1\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'3\', \'1\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'6\', \'1\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'3\', \'2\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'15\', \'2\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'8\', \'2\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'17\', \'3\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'11\', \'3\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'3\', \'3\');')
    op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'6\', \'3\');')
    
    # op.execute('INSERT INTO venue_genres (genre_id, venue_id) VALUES (\'Uncategorized\', \'Uncategorized\');')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genres')
    op.drop_table('shows_list')
    op.drop_table('artist_genres')
    op.drop_table('venues')
    op.drop_table('genres')
    op.drop_table('artists')
    # ### end Alembic commands ###
